vcpkg_from_github(
  OUT_SOURCE_PATH SOURCE_PATH
  REPO  grimfang4/sdl-gpu
  REF v0.12.0
  SHA512 55b23661dec145c4f2c8d44ca6d0dabfc53803fef09668c69b6ea9af6693b1604e25107f1e42f1b75550365734f4c4c25c8a2dc9912fda4f18b1db459575ff80
  HEAD_REF main
  PATCHES
	change-build-paths.patch
)

SET(VCPKG_POLICY_DLLS_WITHOUT_EXPORTS enabled)

vcpkg_configure_cmake(
  SOURCE_PATH "${SOURCE_PATH}"
  PREFER_NINJA
  OPTIONS
	-DCMAKE_INSTALL_INCLUDEDIR=include
)
vcpkg_cmake_build(TARGET src/all ADD_BIN_TO_PATH)

file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/src/include" DESTINATION "${CURRENT_PACKAGES_DIR}/include" RENAME SDL2_gpu FILES_MATCHING PATTERN *.h)

if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/src/lib/SDL2_gpu_s.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/src/lib/SDL2_gpu_s.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
else()
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/src/bin/SDL2_gpu.dll" DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/src/bin/SDL2_gpu.pdb" DESTINATION "${CURRENT_PACKAGES_DIR}/bin")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-rel/src/lib/SDL2_gpu_s.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/lib")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/src/bin/SDL2_gpu.dll" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/src/bin/SDL2_gpu.pdb" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/bin")
    file(INSTALL "${CURRENT_BUILDTREES_DIR}/${TARGET_TRIPLET}-dbg/src/lib/SDL2_gpu_s.lib" DESTINATION "${CURRENT_PACKAGES_DIR}/debug/lib")
endif()

# Handle copyright
file(INSTALL "${SOURCE_PATH}/LICENSE.txt" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
